/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.dhyStoreInfirmatica.view;

import Dao.FabricaConexao;
import br.com.dhyStoreInfirmatica.bean.ItemPedido;
import br.com.dhyStoreInfirmatica.bean.Pedido;
import br.com.dhyStoreInfirmatica.bean.Cliente;
import br.com.dhyStoreInfirmatica.bean.Produto;
import br.com.dhyStoreInfirmatica.dao.ClienteDaoImpl;
import br.com.dhyStoreInfirmatica.dao.ItemPedidoDao;
import br.com.dhyStoreInfirmatica.dao.ItemPedidoDaoImpl;
import br.com.dhyStoreInfirmatica.dao.PedidoDao;
import br.com.dhyStoreInfirmatica.dao.PedidoDaoImpl;
import br.com.dhyStoreInfirmatica.dao.ProdutoDao;
import br.com.dhyStoreInfirmatica.dao.ProdutoDaoImpl;
import static br.com.dhyStoreInfirmatica.view.TelaPrincipal.painelTelaPrincipal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dhyego Pedroso
 */
public class TelaAreaDeVenda extends javax.swing.JInternalFrame {

    FabricaConexao fc = new FabricaConexao();
    EntityManager em = fc.abreConexao("JavaniaStoreInformaticaPU");
    DefaultTableModel defaultTabelaProduto;
    DefaultTableModel defaultTabelaPedido;

    public void setTxtCpf(String txtCpf) {
        this.txtCpf.setText(txtCpf);
    }

    public void setTxtRg(String txtRg) {
        this.txtRg.setText(txtRg);
    }

    public void setTxtNome(String txtNome) {
        this.txtNome.setText(txtNome);
    }

    public void setTxtIdCliente(String txtIdCliente) {
        this.TxtIdCliente.setText(txtIdCliente);
    }

    public TelaAreaDeVenda() {
        initComponents();
        this.pegarDataAtual();
        this.TxtIdCliente.setVisible(false);

        defaultTabelaPedido = (DefaultTableModel) tabelaPedido.getModel();
        tabelaPedido.setRowSorter(new TableRowSorter(defaultTabelaPedido));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisarCliente = new javax.swing.JButton();
        txtRg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtIdCliente = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        btnRemoverItemDoCarrinho = new javax.swing.JButton();
        btnFinalizarPedido = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtPesquisarProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQtdProduto = new javax.swing.JTextField();
        btnAddItemNoCarrinho = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDataCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        boxFormaDePagamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPedido = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Area de Vedas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Nome:");

        txtNome.setEnabled(false);

        btnPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dhyStoreInfirmatica/Icos/usuarioPesquisar.png"))); // NOI18N
        btnPesquisarCliente.setToolTipText("Pesquisar Cliente");
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        txtRg.setEnabled(false);

        jLabel2.setText("CPF:");

        jLabel10.setText("RG:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRg, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txtCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisarCliente)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(7, 7, 7))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnRemoverItemDoCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dhyStoreInfirmatica/Icos/pedidoExcluir.png"))); // NOI18N
        btnRemoverItemDoCarrinho.setToolTipText("Remover Item do Carrinho");
        btnRemoverItemDoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemDoCarrinhoActionPerformed(evt);
            }
        });

        btnFinalizarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dhyStoreInfirmatica/Icos/pedidoFinalizar.png"))); // NOI18N
        btnFinalizarPedido.setToolTipText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dhyStoreInfirmatica/Icos/pedidoSair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSair)
                    .addComponent(btnRemoverItemDoCarrinho)
                    .addComponent(btnFinalizarPedido))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverItemDoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtPesquisarProduto.setToolTipText("Pesquisar Produto");
        txtPesquisarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarProdutoKeyReleased(evt);
            }
        });

        jLabel4.setText("Produto:");

        jLabel9.setText("Quantidade:");

        btnAddItemNoCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dhyStoreInfirmatica/Icos/pedidoAdd.png"))); // NOI18N
        btnAddItemNoCarrinho.setToolTipText("Add produto ao Carrinho");
        btnAddItemNoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemNoCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddItemNoCarrinho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddItemNoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("Data:");

        txtDataCompra.setEnabled(false);

        jLabel7.setText("Forma de Pagamento:");

        boxFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "À Vista", "A Prazo", "Cartão de Credito", "Cartão de Débito" }));

        jLabel3.setText("TOTAL:");

        txtValorTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxFormaDePagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "iD", "Produto", "Descrição", "Valor", "Marca", "Quantidade", "Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(tabelaProduto);

        tabelaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID do Produto", "Produto", "Descrição", "Marca", "Quantidade", "Valor Unit.", "Valor Total"
            }
        ));
        jScrollPane2.setViewportView(tabelaPedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        try {

            TelaPesquisarClientes telaPesquisarClientes = new TelaPesquisarClientes(this);
            TelaPrincipal.painelTelaPrincipal.add(telaPesquisarClientes);
            telaPesquisarClientes.setVisible(true);

            telaPesquisarClientes.setSelected(true);
            telaPesquisarClientes.setMaximizable(true);
            telaPesquisarClientes.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {

        }

//        this.dispose();
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void btnAddItemNoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemNoCarrinhoActionPerformed
        if (tabelaProduto.getSelectedRow() != -1) {
            if (Integer.parseInt(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 5).toString()) == 0) {
                JOptionPane.showMessageDialog(this, "Estoque zero");

            } else if (Integer.parseInt(txtQtdProduto.getText()) > Integer.parseInt(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 5).toString())) {
                JOptionPane.showMessageDialog(this, "Estoque Insuficiente");

            } else if (Integer.parseInt(txtQtdProduto.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Quantidade errada");

            } else {
                String id = String.valueOf(this.tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 0));
                String nome = (String) this.tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 1);
                String desc = (String) this.tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 2);
                String marca = (String) this.tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 4);
                String qtd = txtQtdProduto.getText();
                String valorUnit = String.valueOf(this.tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 3));
                double valarTotal = Double.parseDouble(valorUnit) * Double.parseDouble(qtd);

                this.valorTotalDoPedido = valorTotalDoPedido + valarTotal;

                txtValorTotal.setText(String.valueOf(valorTotalDoPedido));

                this.addItemAoCarrinho(id, nome, desc, qtd, marca, valorUnit, String.valueOf(valarTotal));

                txtPesquisarProduto.setText("");
                txtQtdProduto.setText("");
                defaultTabelaProduto.setNumRows(0);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Produto para add ao carrinho!!");
        }
    }//GEN-LAST:event_btnAddItemNoCarrinhoActionPerformed

    private void btnRemoverItemDoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemDoCarrinhoActionPerformed
        if (tabelaPedido.getSelectedRow() != -1) {
            txtValorTotal.setText(String.valueOf(Double.parseDouble(txtValorTotal.getText()) - (Double.parseDouble(this.tabelaPedido.getValueAt(tabelaPedido.getSelectedRow(), 6).toString()))));
            this.valorTotalDoPedido -= Double.parseDouble(this.tabelaPedido.getValueAt(tabelaPedido.getSelectedRow(), 6).toString());
            defaultTabelaPedido.removeRow(tabelaPedido.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoverItemDoCarrinhoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed

        if (txtNome.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Qual é o Cliente??");

        } else if (boxFormaDePagamento.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(this, "Qual a forma de pagamento!!");

        } else if (tabelaPedido.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "O carrinho esta vazio!!");

        } else {
            Pedido pedido = new Pedido();
            PedidoDao pedidoDao = new PedidoDaoImpl(em);

            ItemPedido itemPedido;
            ItemPedidoDao itemPedidoDao = new ItemPedidoDaoImpl(em);

            Produto produto;
            ProdutoDao produtoDao = new ProdutoDaoImpl(em);

            pedido.setCliente(new Cliente());
            pedido.getCliente().setIdCliente(Integer.parseInt(TxtIdCliente.getText()));
            pedido.setValorTotalVenda(Double.parseDouble(txtValorTotal.getText()));
            pedido.setTipoPagamento(String.valueOf(boxFormaDePagamento.getSelectedItem()));
            pedido.setDataCompra(new Date());
            pedidoDao.salvar(pedido);
            for (int item = 0; item < tabelaPedido.getRowCount(); item++) {
                itemPedido = new ItemPedido();

                itemPedido.setPedido(new Pedido());
                itemPedido.getPedido().setIdPedido(pedido.getIdPedido());
                itemPedido.setProduto(new Produto());
                itemPedido.getProduto().setIdProduto(Integer.parseInt(tabelaPedido.getValueAt(item, 0).toString()));
                itemPedido.setQtdDeItem(Integer.parseInt(tabelaPedido.getValueAt(item, 4).toString()));
                itemPedido.setValorUnit(Double.parseDouble(tabelaPedido.getValueAt(item, 5).toString()));

                itemPedidoDao.salvar(itemPedido);

                int idProduto = Integer.parseInt(tabelaPedido.getValueAt(item, 0).toString());
                produto = (Produto) produtoDao.pesquisarPorId(Produto.class, idProduto);
                produto.setQtdProduto(produto.getQtdProduto() - Integer.parseInt(tabelaPedido.getValueAt(item, 4).toString()));
                produtoDao.alterar(produto);
            }
            this.limparCampos();
            JOptionPane.showMessageDialog(this, "Sucesso!!");
        }

    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        em.close();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtPesquisarProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoKeyReleased
        pesquisarProduto(txtPesquisarProduto.getText());
    }//GEN-LAST:event_txtPesquisarProdutoKeyReleased

    private void txtCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyReleased
        pesquisarCliente(txtCpf.getText());
    }//GEN-LAST:event_txtCpfKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtIdCliente;
    private javax.swing.JComboBox<String> boxFormaDePagamento;
    private javax.swing.JButton btnAddItemNoCarrinho;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnRemoverItemDoCarrinho;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaPedido;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtDataCompra;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisarProduto;
    private javax.swing.JTextField txtQtdProduto;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
double valorTotalDoPedido;

    public void pesquisarProduto(String pesquisa) {
        defaultTabelaProduto = (DefaultTableModel) tabelaProduto.getModel();
        defaultTabelaProduto.setNumRows(0);
        ProdutoDao produtoDao = new ProdutoDaoImpl(em);
        List<br.com.dhyStoreInfirmatica.bean.Produto> produtos;

        produtos = produtoDao.pesquisarProduto(pesquisa);

        for (br.com.dhyStoreInfirmatica.bean.Produto p : produtos) {
            defaultTabelaProduto.addRow(new Object[]{
                p.getIdProduto(),
                p.getNomeProduto(),
                p.getDescProduto(),
                p.getValorProduto(),
                p.getMarca().getNomeMarca(),
                p.getQtdProduto(),
                p.getFornecedor().getNomeFornecedor()
            });
        }
    }

    public void addItemAoCarrinho(String id, String nome, String desc, String marca, String qtd, String valorUnit, String valorTotal) {

        defaultTabelaPedido.addRow(new Object[]{id, nome, desc, qtd, marca, valorUnit, valorTotal});

    }

    public void pegarDataAtual() {
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        txtDataCompra.setText(formatador.format(data));
    }

    public void limparCampos() {
        txtNome.setText("");
        txtCpf.setText("");
        txtRg.setText("");
        txtPesquisarProduto.setText("");
        txtQtdProduto.setText("");
        txtValorTotal.setText("0,00");
        defaultTabelaPedido.setNumRows(0);
        this.valorTotalDoPedido = 0;

    }

    public void pesquisarCliente(String pesquisa) {
        ClienteDaoImpl clienteDao = new ClienteDaoImpl(em);
        List<Cliente> clientes = clienteDao.pesquisarCpf(pesquisa);

        for (Cliente c : clientes) {
            txtNome.setText(c.getNomeCliente());
            txtRg.setText(c.getRgCliente());
        }
    }
}
